# Tarea 11

Repositorio: https://github.com/KennethJYS/Tarea-11

In [1]:
%load_ext autoreload
import numpy as np
from src import gauss_jacobi,gauss_seidel

[02-06 10:56:02][INFO] 2025-02-06 10:56:02.679047
[02-06 10:56:02][INFO] 2025-02-06 10:56:02.681917


### Ejercicio 1

a

In [2]:
%autoreload 2
A = [[3,-1,1],[3,6,2],[3,3,7]]
b = np.array([1,0,4])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:02][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:02][INFO] i= 1 x: [[0.33333333 0.         0.57142857]]
[02-06 10:56:02][INFO] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]


(array([[ 0.14285714],
        [-0.35714286],
        [ 0.42857143]]),
 [array([0., 0., 0.]),
  array([[0.33333333],
         [0.        ],
         [0.57142857]]),
  array([[ 0.14285714],
         [-0.35714286],
         [ 0.42857143]])])

b

In [3]:
%autoreload 2
A = [[10,-1,0],[-1,10,-2],[0,-2,10]]
b = np.array([9,7,6])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:02][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:02][INFO] i= 1 x: [[0.9 0.7 0.6]]
[02-06 10:56:02][INFO] i= 2 x: [[0.97 0.91 0.74]]


(array([[0.97],
        [0.91],
        [0.74]]),
 [array([0., 0., 0.]),
  array([[0.9],
         [0.7],
         [0.6]]),
  array([[0.97],
         [0.91],
         [0.74]])])

c

In [4]:
%autoreload 2
A = [[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]]
b = np.array([6,25,-11,-11])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:02][INFO] i= 0 x: [0. 0. 0. 0.]
[02-06 10:56:02][INFO] i= 1 x: [[ 0.6    2.5   -1.375 -2.2  ]]
[02-06 10:56:02][INFO] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]


(array([[-0.65 ],
        [ 1.65 ],
        [-0.4  ],
        [-2.475]]),
 [array([0., 0., 0., 0.]),
  array([[ 0.6  ],
         [ 2.5  ],
         [-1.375],
         [-2.2  ]]),
  array([[-0.65 ],
         [ 1.65 ],
         [-0.4  ],
         [-2.475]])])

d

In [5]:
%autoreload 2
A = [[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]
b = np.array([6,6,6,6,6])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:02][INFO] i= 0 x: [0. 0. 0. 0. 0.]
[02-06 10:56:02][INFO] i= 1 x: [[ 1.5 -2.   1.2  1.5  1.5]]
[02-06 10:56:02][INFO] i= 2 x: [[ 1.325 -1.6    1.6    1.675  2.425]]


(array([[ 1.325],
        [-1.6  ],
        [ 1.6  ],
        [ 1.675],
        [ 2.425]]),
 [array([0., 0., 0., 0., 0.]),
  array([[ 1.5],
         [-2. ],
         [ 1.2],
         [ 1.5],
         [ 1.5]]),
  array([[ 1.325],
         [-1.6  ],
         [ 1.6  ],
         [ 1.675],
         [ 2.425]])])

## Ejercicio 2

a

In [6]:
%autoreload 2
A = [[3,-1,1],[3,6,2],[3,3,7]]
b = np.array([1,0,4])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[02-06 10:56:03][INFO] i= 2 x: [[ 0.11111111 -0.22222222  0.61904762]]


(array([[ 0.11111111],
        [-0.22222222],
        [ 0.61904762]]),
 [array([0., 0., 0.]),
  array([[ 0.33333333],
         [-0.16666667],
         [ 0.5       ]]),
  array([[ 0.11111111],
         [-0.22222222],
         [ 0.61904762]])])

b

In [7]:
%autoreload 2
A = [[10,-1,0],[-1,10,-2],[0,-2,10]]
b = np.array([9,7,6])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[0.9   0.79  0.758]]
[02-06 10:56:03][INFO] i= 2 x: [[0.979  0.9495 0.7899]]


(array([[0.979 ],
        [0.9495],
        [0.7899]]),
 [array([0., 0., 0.]),
  array([[0.9  ],
         [0.79 ],
         [0.758]]),
  array([[0.979 ],
         [0.9495],
         [0.7899]])])

c

In [8]:
%autoreload 2
A = [[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]]
b = np.array([6,25,-11,-11])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[02-06 10:56:03][INFO] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]


(array([[-0.5     ],
        [ 2.64    ],
        [-0.336875],
        [-2.267375]]),
 [array([0., 0., 0., 0.]),
  array([[ 0.6  ],
         [ 2.2  ],
         [-0.275],
         [-2.255]]),
  array([[-0.5     ],
         [ 2.64    ],
         [-0.336875],
         [-2.267375]])])

d

In [9]:
%autoreload 2
A = [[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]
b = np.array([6,6,6,6,6])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 1.5     -2.5      1.1      1.525    2.64375]]
[02-06 10:56:03][INFO] i= 2 x: [[ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]]


(array([[ 1.1890625 ],
        [-1.52135417],
        [ 1.86239583],
        [ 1.88252604],
        [ 2.25564453]]),
 [array([0., 0., 0., 0., 0.]),
  array([[ 1.5    ],
         [-2.5    ],
         [ 1.1    ],
         [ 1.525  ],
         [ 2.64375]]),
  array([[ 1.1890625 ],
         [-1.52135417],
         [ 1.86239583],
         [ 1.88252604],
         [ 2.25564453]])])

## Ejercicio 3

In [10]:
A = [[3,-1,1],[3,6,2],[3,3,7]]
b = np.array([1,0,4])
x0 = np.zeros(len(b)) 
max_iter = 100
tol = 10e-3
gauss_jacobi(A=A, b=b, x0=x0, tol=tol,max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[0.33333333 0.         0.57142857]]
[02-06 10:56:03][INFO] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]
[02-06 10:56:03][INFO] i= 3 x: [[ 0.07142857 -0.21428571  0.66326531]]
[02-06 10:56:03][INFO] i= 4 x: [[ 0.04081633 -0.25680272  0.63265306]]
[02-06 10:56:03][INFO] i= 5 x: [[ 0.03684807 -0.23129252  0.66399417]]
[02-06 10:56:03][INFO] i= 6 x: [[ 0.03490444 -0.23975543  0.6547619 ]]


(array([[ 0.03516089],
        [-0.23570619],
        [ 0.65922185]]),
 [array([0., 0., 0.]),
  array([[0.33333333],
         [0.        ],
         [0.57142857]]),
  array([[ 0.14285714],
         [-0.35714286],
         [ 0.42857143]]),
  array([[ 0.07142857],
         [-0.21428571],
         [ 0.66326531]]),
  array([[ 0.04081633],
         [-0.25680272],
         [ 0.63265306]]),
  array([[ 0.03684807],
         [-0.23129252],
         [ 0.66399417]]),
  array([[ 0.03490444],
         [-0.23975543],
         [ 0.6547619 ]])])

b

In [11]:
%autoreload 2
A = [[10,-1,0],[-1,10,-2],[0,-2,10]]
b = np.array([9,7,6])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[0.9 0.7 0.6]]
[02-06 10:56:03][INFO] i= 2 x: [[0.97 0.91 0.74]]
[02-06 10:56:03][INFO] i= 3 x: [[0.991 0.945 0.782]]
[02-06 10:56:03][INFO] i= 4 x: [[0.9945 0.9555 0.789 ]]


(array([[0.99555],
        [0.95725],
        [0.7911 ]]),
 [array([0., 0., 0.]),
  array([[0.9],
         [0.7],
         [0.6]]),
  array([[0.97],
         [0.91],
         [0.74]]),
  array([[0.991],
         [0.945],
         [0.782]]),
  array([[0.9945],
         [0.9555],
         [0.789 ]])])

c

In [12]:
%autoreload 2
A = [[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]]
b = np.array([6,25,-11,-11])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 0.6    2.5   -1.375 -2.2  ]]
[02-06 10:56:03][INFO] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]
[02-06 10:56:03][INFO] i= 3 x: [[-0.225     2.665    -0.859375 -2.28    ]]
[02-06 10:56:03][INFO] i= 4 x: [[-0.7325    2.26875  -0.3275   -2.371875]]
[02-06 10:56:03][INFO] i= 5 x: [[-0.534375    2.73525    -0.53710938 -2.2655    ]]
[02-06 10:56:03][INFO] i= 6 x: [[-0.767625    2.55234375 -0.2905625  -2.30742188]]
[02-06 10:56:03][INFO] i= 7 x: [[-0.67617187  2.7675875  -0.38725586 -2.2581125 ]]
[02-06 10:56:03][INFO] i= 8 x: [[-0.78379375  2.68318359 -0.27347031 -2.27745117]]
[02-06 10:56:03][INFO] i= 9 x: [[-0.7415918   2.78250875 -0.3180896  -2.25469406]]
[02-06 10:56:03][INFO] i= 10 x: [[-0.79125437  2.74356006 -0.26558238 -2.26361792]]
[02-06 10:56:03][INFO] i= 11 x: [[-0.77178003  2.78939423 -0.28617221 -2.25311648]]
[02-06 10:56:03][INFO] i= 12 x: [[-0.79469712  2.77142113 -0.26194244 -2.25723444]]
[02-06 10:56

(array([[-0.79701889],
        [ 2.79021057],
        [-0.25948768],
        [-2.25292944]]),
 [array([0., 0., 0., 0.]),
  array([[ 0.6  ],
         [ 2.5  ],
         [-1.375],
         [-2.2  ]]),
  array([[-0.65 ],
         [ 1.65 ],
         [-0.4  ],
         [-2.475]]),
  array([[-0.225   ],
         [ 2.665   ],
         [-0.859375],
         [-2.28    ]]),
  array([[-0.7325  ],
         [ 2.26875 ],
         [-0.3275  ],
         [-2.371875]]),
  array([[-0.534375  ],
         [ 2.73525   ],
         [-0.53710938],
         [-2.2655    ]]),
  array([[-0.767625  ],
         [ 2.55234375],
         [-0.2905625 ],
         [-2.30742188]]),
  array([[-0.67617187],
         [ 2.7675875 ],
         [-0.38725586],
         [-2.2581125 ]]),
  array([[-0.78379375],
         [ 2.68318359],
         [-0.27347031],
         [-2.27745117]]),
  array([[-0.7415918 ],
         [ 2.78250875],
         [-0.3180896 ],
         [-2.25469406]]),
  array([[-0.79125437],
         [ 2.74356006],
     

d

In [13]:
%autoreload 2
A = [[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]
b = np.array([6,6,6,6,6])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 1.5 -2.   1.2  1.5  1.5]]
[02-06 10:56:03][INFO] i= 2 x: [[ 1.325 -1.6    1.6    1.675  2.425]]
[02-06 10:56:03][INFO] i= 3 x: [[ 0.89375 -1.35     1.81     1.83125  2.28125]]
[02-06 10:56:03][INFO] i= 4 x: [[ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]]
[02-06 10:56:03][INFO] i= 5 x: [[ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]]
[02-06 10:56:03][INFO] i= 6 x: [[ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]]
[02-06 10:56:03][INFO] i= 7 x: [[ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]]
[02-06 10:56:03][INFO] i= 8 x: [[ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]]
[02-06 10:56:03][INFO] i= 9 x: [[ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]]


(array([[ 0.78718101],
        [-1.00174151],
        [ 1.8658388 ],
        [ 1.91274157],
        [ 1.98672138]]),
 [array([0., 0., 0., 0., 0.]),
  array([[ 1.5],
         [-2. ],
         [ 1.2],
         [ 1.5],
         [ 1.5]]),
  array([[ 1.325],
         [-1.6  ],
         [ 1.6  ],
         [ 1.675],
         [ 2.425]]),
  array([[ 0.89375],
         [-1.35   ],
         [ 1.81   ],
         [ 1.83125],
         [ 2.28125]]),
  array([[ 0.8146875 ],
         [-1.08416667],
         [ 1.935     ],
         [ 1.8384375 ],
         [ 2.1696875 ]]),
  array([[ 0.74486979],
         [-1.01375   ],
         [ 1.89258333],
         [ 1.91638021],
         [ 2.06622396]]),
  array([[ 0.76373568],
         [-0.97863542],
         [ 1.90132292],
         [ 1.90592578],
         [ 2.00092578]]),
  array([[ 0.76909668],
         [-0.98549566],
         [ 1.87160313],
         [ 1.92160579],
         [ 1.98816699]]),
  array([[ 0.78143139],
         [-0.99196259],
         [ 1.87141502],
 

## Ejercicio 4

a

In [14]:
%autoreload 2
A = [[3,-1,1],[3,6,2],[3,3,7]]
b = np.array([1,0,4])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[02-06 10:56:03][INFO] i= 2 x: [[ 0.11111111 -0.22222222  0.61904762]]
[02-06 10:56:03][INFO] i= 3 x: [[ 0.05291005 -0.23280423  0.64852608]]
[02-06 10:56:03][INFO] i= 4 x: [[ 0.03955656 -0.23595364  0.65559875]]


(array([[ 0.0361492 ],
        [-0.23660752],
        [ 0.65733928]]),
 [array([0., 0., 0.]),
  array([[ 0.33333333],
         [-0.16666667],
         [ 0.5       ]]),
  array([[ 0.11111111],
         [-0.22222222],
         [ 0.61904762]]),
  array([[ 0.05291005],
         [-0.23280423],
         [ 0.64852608]]),
  array([[ 0.03955656],
         [-0.23595364],
         [ 0.65559875]])])

b

In [15]:
%autoreload 2
A = [[10,-1,0],[-1,10,-2],[0,-2,10]]
b = np.array([9,7,6])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:03][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:03][INFO] i= 1 x: [[0.9   0.79  0.758]]
[02-06 10:56:03][INFO] i= 2 x: [[0.979  0.9495 0.7899]]
[02-06 10:56:03][INFO] i= 3 x: [[0.99495  0.957475 0.791495]]


(array([[0.9957475 ],
        [0.95787375],
        [0.79157475]]),
 [array([0., 0., 0.]),
  array([[0.9  ],
         [0.79 ],
         [0.758]]),
  array([[0.979 ],
         [0.9495],
         [0.7899]]),
  array([[0.99495 ],
         [0.957475],
         [0.791495]])])

c

In [16]:
%autoreload 2
A = [[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]]
b = np.array([6,25,-11,-11])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:04][INFO] i= 0 x: [0. 0. 0. 0.]
[02-06 10:56:04][INFO] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[02-06 10:56:04][INFO] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]
[02-06 10:56:04][INFO] i= 3 x: [[-0.72        2.72525    -0.29579687 -2.25915938]]
[02-06 10:56:04][INFO] i= 4 x: [[-0.762625    2.76299375 -0.27589805 -2.25517961]]
[02-06 10:56:04][INFO] i= 5 x: [[-0.78149687  2.78038922 -0.26670284 -2.25334057]]
[02-06 10:56:04][INFO] i= 6 x: [[-0.79019461  2.78841617 -0.26245949 -2.2524919 ]]


(array([[-0.79420808],
        [ 2.79212025],
        [-0.26050136],
        [-2.25210027]]),
 [array([0., 0., 0., 0.]),
  array([[ 0.6  ],
         [ 2.2  ],
         [-0.275],
         [-2.255]]),
  array([[-0.5     ],
         [ 2.64    ],
         [-0.336875],
         [-2.267375]]),
  array([[-0.72      ],
         [ 2.72525   ],
         [-0.29579687],
         [-2.25915938]]),
  array([[-0.762625  ],
         [ 2.76299375],
         [-0.27589805],
         [-2.25517961]]),
  array([[-0.78149687],
         [ 2.78038922],
         [-0.26670284],
         [-2.25334057]]),
  array([[-0.79019461],
         [ 2.78841617],
         [-0.26245949],
         [-2.2524919 ]])])

d

In [17]:
%autoreload 2
A = [[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]
b = np.array([6,6,6,6,6])
x0=np.zeros(len(b))
max_iter = 100
tol = 10e-3

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:04][INFO] i= 0 x: [0. 0. 0. 0. 0.]
[02-06 10:56:04][INFO] i= 1 x: [[ 1.5     -2.5      1.1      1.525    2.64375]]
[02-06 10:56:04][INFO] i= 2 x: [[ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]]
[02-06 10:56:04][INFO] i= 3 x: [[ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]]
[02-06 10:56:04][INFO] i= 4 x: [[ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]]
[02-06 10:56:04][INFO] i= 5 x: [[ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]]


(array([[ 0.78616258],
        [-1.00240703],
        [ 1.86606999],
        [ 1.91245638],
        [ 1.98960692]]),
 [array([0., 0., 0., 0., 0.]),
  array([[ 1.5    ],
         [-2.5    ],
         [ 1.1    ],
         [ 1.525  ],
         [ 2.64375]]),
  array([[ 1.1890625 ],
         [-1.52135417],
         [ 1.86239583],
         [ 1.88252604],
         [ 2.25564453]]),
  array([[ 0.85082845],
         [-1.03530219],
         [ 1.89436317],
         [ 1.92747236],
         [ 2.0093738 ]]),
  array([[ 0.7828913 ],
         [-0.98701859],
         [ 1.87161643],
         [ 1.91687229],
         [ 1.98219533]]),
  array([[ 0.78330171],
         [-0.998271  ],
         [ 1.86614704],
         [ 1.91279444],
         [ 1.98747365]])])

## Ejercicio 5

a

In [18]:
%autoreload 2
A = [[2,-1,1],[2,2,2,],[-1,-1,2]]
b = [-1,4,-5]
x0 = np.zeros(len(b))
tol = 10e-3
max_iter = 26

try:
    gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)
except ValueError as e:
    print(e)

[02-06 10:56:04][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:04][INFO] i= 1 x: [[-0.5  2.  -2.5]]
[02-06 10:56:04][INFO] i= 2 x: [[ 1.75  5.   -1.75]]
[02-06 10:56:04][INFO] i= 3 x: [[2.875 2.    0.875]]
[02-06 10:56:04][INFO] i= 4 x: [[ 0.0625 -1.75   -0.0625]]
[02-06 10:56:04][INFO] i= 5 x: [[-1.34375  2.      -3.34375]]
[02-06 10:56:04][INFO] i= 6 x: [[ 2.171875  6.6875   -2.171875]]
[02-06 10:56:04][INFO] i= 7 x: [[3.9296875 2.        1.9296875]]
[02-06 10:56:04][INFO] i= 8 x: [[-0.46484375 -3.859375    0.46484375]]
[02-06 10:56:04][INFO] i= 9 x: [[-2.66210938  2.         -4.66210938]]
[02-06 10:56:04][INFO] i= 10 x: [[ 2.83105469  9.32421875 -2.83105469]]
[02-06 10:56:04][INFO] i= 11 x: [[5.57763672 2.         3.57763672]]
[02-06 10:56:04][INFO] i= 12 x: [[-1.28881836 -7.15527344  1.28881836]]
[02-06 10:56:04][INFO] i= 13 x: [[-4.7220459  2.        -6.7220459]]
[02-06 10:56:04][INFO] i= 14 x: [[ 3.86102295 13.4440918  -3.86102295]]
[02-06 10:56:04][INFO] i= 15 x: [[8.15255737 2.        

Podemos ver que el método convergé dentro de las 25 iteraciones pero la respuesta que nos dá no es la correcta

b

In [19]:
tol=10e-5
gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:04][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:04][INFO] i= 1 x: [[-0.5  2.5 -1.5]]
[02-06 10:56:04][INFO] i= 2 x: [[ 1.5   2.   -0.75]]
[02-06 10:56:04][INFO] i= 3 x: [[ 0.875  1.875 -1.125]]
[02-06 10:56:04][INFO] i= 4 x: [[ 1.      2.125  -0.9375]]
[02-06 10:56:04][INFO] i= 5 x: [[ 1.03125  1.90625 -1.03125]]
[02-06 10:56:04][INFO] i= 6 x: [[ 0.96875   2.0625   -0.984375]]
[02-06 10:56:04][INFO] i= 7 x: [[ 1.0234375  1.9609375 -1.0078125]]
[02-06 10:56:04][INFO] i= 8 x: [[ 0.984375    2.0234375  -0.99609375]]
[02-06 10:56:04][INFO] i= 9 x: [[ 1.00976562  1.98632812 -1.00195312]]
[02-06 10:56:04][INFO] i= 10 x: [[ 0.99414062  2.0078125  -0.99902344]]
[02-06 10:56:04][INFO] i= 11 x: [[ 1.00341797  1.99560547 -1.00048828]]
[02-06 10:56:04][INFO] i= 12 x: [[ 0.99804688  2.00244141 -0.99975586]]
[02-06 10:56:04][INFO] i= 13 x: [[ 1.00109863  1.99865723 -1.00012207]]
[02-06 10:56:04][INFO] i= 14 x: [[ 0.99938965  2.00073242 -0.99993896]]
[02-06 10:56:04][INFO] i= 15 x: [[ 1.000335

(array([[ 0.99998474],
        [ 2.00001717],
        [-0.99999905]]),
 [array([0., 0., 0.]),
  array([[-0.5],
         [ 2.5],
         [-1.5]]),
  array([[ 1.5 ],
         [ 2.  ],
         [-0.75]]),
  array([[ 0.875],
         [ 1.875],
         [-1.125]]),
  array([[ 1.    ],
         [ 2.125 ],
         [-0.9375]]),
  array([[ 1.03125],
         [ 1.90625],
         [-1.03125]]),
  array([[ 0.96875 ],
         [ 2.0625  ],
         [-0.984375]]),
  array([[ 1.0234375],
         [ 1.9609375],
         [-1.0078125]]),
  array([[ 0.984375  ],
         [ 2.0234375 ],
         [-0.99609375]]),
  array([[ 1.00976562],
         [ 1.98632812],
         [-1.00195312]]),
  array([[ 0.99414062],
         [ 2.0078125 ],
         [-0.99902344]]),
  array([[ 1.00341797],
         [ 1.99560547],
         [-1.00048828]]),
  array([[ 0.99804688],
         [ 2.00244141],
         [-0.99975586]]),
  array([[ 1.00109863],
         [ 1.99865723],
         [-1.00012207]]),
  array([[ 0.99938965],
    

## Ejercicio 6

a

La matriz no es estrictamente dominante en la diagonal, esto debido a que en la diagonal no hay numeros mayores a la suma del valor absoluto del resto de numeros.

b

In [20]:
%autoreload 2
A = [[1,0,-1],[-0.5,1,-0.25,],[1,-0.5,1]]
b = [0.2,-1.425,2]
x0 = np.zeros(len(b))
tol = 10e-22
max_iter = 300

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:04][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:04][INFO] i= 1 x: [[ 0.2    -1.325   1.1375]]
[02-06 10:56:04][INFO] i= 2 x: [[ 1.3375    -0.471875   0.4265625]]
[02-06 10:56:04][INFO] i= 3 x: [[ 0.6265625  -1.00507812  0.87089844]]
[02-06 10:56:04][INFO] i= 4 x: [[ 1.07089844 -0.67182617  0.59318848]]
[02-06 10:56:04][INFO] i= 5 x: [[ 0.79318848 -0.88010864  0.7667572 ]]
[02-06 10:56:04][INFO] i= 6 x: [[ 0.9667572  -0.7499321   0.65827675]]
[02-06 10:56:04][INFO] i= 7 x: [[ 0.85827675 -0.83129244  0.72607703]]
[02-06 10:56:04][INFO] i= 8 x: [[ 0.92607703 -0.78044223  0.68370185]]
[02-06 10:56:04][INFO] i= 9 x: [[ 0.88370185 -0.81222361  0.71018634]]
[02-06 10:56:04][INFO] i= 10 x: [[ 0.91018634 -0.79236024  0.69363354]]
[02-06 10:56:04][INFO] i= 11 x: [[ 0.89363354 -0.80477485  0.70397904]]
[02-06 10:56:04][INFO] i= 12 x: [[ 0.90397904 -0.79701572  0.6975131 ]]
[02-06 10:56:04][INFO] i= 13 x: [[ 0.8975131  -0.80186517  0.70155431]]
[02-06 10:56:04][INFO] i= 14 x: [[ 0.90155431 

(array([[ 0.9],
        [-0.8],
        [ 0.7]]),
 [array([0., 0., 0.]),
  array([[ 0.2   ],
         [-1.325 ],
         [ 1.1375]]),
  array([[ 1.3375   ],
         [-0.471875 ],
         [ 0.4265625]]),
  array([[ 0.6265625 ],
         [-1.00507812],
         [ 0.87089844]]),
  array([[ 1.07089844],
         [-0.67182617],
         [ 0.59318848]]),
  array([[ 0.79318848],
         [-0.88010864],
         [ 0.7667572 ]]),
  array([[ 0.9667572 ],
         [-0.7499321 ],
         [ 0.65827675]]),
  array([[ 0.85827675],
         [-0.83129244],
         [ 0.72607703]]),
  array([[ 0.92607703],
         [-0.78044223],
         [ 0.68370185]]),
  array([[ 0.88370185],
         [-0.81222361],
         [ 0.71018634]]),
  array([[ 0.91018634],
         [-0.79236024],
         [ 0.69363354]]),
  array([[ 0.89363354],
         [-0.80477485],
         [ 0.70397904]]),
  array([[ 0.90397904],
         [-0.79701572],
         [ 0.6975131 ]]),
  array([[ 0.8975131 ],
         [-0.80186517],
      

Si es con 10e22 no sale pero si es 10e-22 si converge y encuentra la respuesta correcta

c

In [21]:
%autoreload 2
A = [[1,0,-2],[-0.5,1,-0.25,],[1,-0.5,1]]
b = [0.2,-1.425,2]
x0 = np.zeros(len(b))
tol = 10e-22
max_iter = 300

gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:05][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:05][INFO] i= 1 x: [[ 0.2    -1.325   1.1375]]
[02-06 10:56:05][INFO] i= 2 x: [[ 2.475      0.096875  -0.4265625]]
[02-06 10:56:05][INFO] i= 3 x: [[-0.653125   -1.85820313  1.72402344]]
[02-06 10:56:05][INFO] i= 4 x: [[ 3.64804688  0.8300293  -1.23303223]]
[02-06 10:56:05][INFO] i= 5 x: [[-2.26606445 -2.86629028  2.83291931]]
[02-06 10:56:05][INFO] i= 6 x: [[ 5.86583862  2.21614914 -2.75776405]]
[02-06 10:56:05][INFO] i= 7 x: [[-5.31552811 -4.77220507  4.92942557]]
[02-06 10:56:05][INFO] i= 8 x: [[10.05885115  4.83678197 -5.64046016]]
[02-06 10:56:05][INFO] i= 9 x: [[-11.08092033  -8.3755752    8.89313272]]
[02-06 10:56:05][INFO] i= 10 x: [[ 17.98626545   9.79141591 -11.0905575 ]]
[02-06 10:56:05][INFO] i= 11 x: [[-21.98111499 -15.18819687  16.38701656]]
[02-06 10:56:05][INFO] i= 12 x: [[ 32.97403311  19.1587707  -21.39464777]]
[02-06 10:56:05][INFO] i= 13 x: [[-42.58929553 -28.06830971  30.55514068]]
[02-06 10:56:05][INFO] i= 14 x:

(array([[-1.56863478e+41],
        [-9.80396739e+40],
        [ 1.07843641e+41]]),
 [array([0., 0., 0.]),
  array([[ 0.2   ],
         [-1.325 ],
         [ 1.1375]]),
  array([[ 2.475    ],
         [ 0.096875 ],
         [-0.4265625]]),
  array([[-0.653125  ],
         [-1.85820313],
         [ 1.72402344]]),
  array([[ 3.64804688],
         [ 0.8300293 ],
         [-1.23303223]]),
  array([[-2.26606445],
         [-2.86629028],
         [ 2.83291931]]),
  array([[ 5.86583862],
         [ 2.21614914],
         [-2.75776405]]),
  array([[-5.31552811],
         [-4.77220507],
         [ 4.92942557]]),
  array([[10.05885115],
         [ 4.83678197],
         [-5.64046016]]),
  array([[-11.08092033],
         [ -8.3755752 ],
         [  8.89313272]]),
  array([[ 17.98626545],
         [  9.79141591],
         [-11.0905575 ]]),
  array([[-21.98111499],
         [-15.18819687],
         [ 16.38701656]]),
  array([[ 32.97403311],
         [ 19.1587707 ],
         [-21.39464777]]),
  array([

Si se cambia a este converge a otra respuesta

## Ejercicio 7

a

In [22]:
%autoreload 2
A = [[1,0,-1],[-0.5,1,-0.25,],[1,-0.5,1]]
b = [0.2,-1.425,2]
x0 = np.zeros(len(b))
tol = 10e-22
max_iter = 300

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:05][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:05][INFO] i= 1 x: [[ 0.2   -1.425  2.   ]]
[02-06 10:56:05][INFO] i= 2 x: [[ 2.2    -0.825   1.0875]]
[02-06 10:56:05][INFO] i= 3 x: [[ 1.2875   -0.053125 -0.6125  ]]
[02-06 10:56:05][INFO] i= 4 x: [[-0.4125    -0.934375   0.6859375]]
[02-06 10:56:05][INFO] i= 5 x: [[ 0.8859375  -1.45976563  1.9453125 ]]
[02-06 10:56:05][INFO] i= 6 x: [[ 2.1453125  -0.49570312  0.38417969]]
[02-06 10:56:05][INFO] i= 7 x: [[ 0.58417969 -0.25629883 -0.39316406]]
[02-06 10:56:05][INFO] i= 8 x: [[-0.19316406 -1.23120117  1.2876709 ]]
[02-06 10:56:05][INFO] i= 9 x: [[ 1.4876709  -1.19966431  1.57756348]]
[02-06 10:56:05][INFO] i= 10 x: [[ 1.77756348 -0.28677368 -0.08750305]]
[02-06 10:56:05][INFO] i= 11 x: [[ 0.11249695 -0.55809402  0.07904968]]
[02-06 10:56:05][INFO] i= 12 x: [[ 0.27904968 -1.34898911  1.60845604]]
[02-06 10:56:05][INFO] i= 13 x: [[ 1.80845604 -0.88336115  1.04645576]]
[02-06 10:56:05][INFO] i= 14 x: [[ 1.24645576 -0.25915804 -0.250136

(array([[ 0.89979164],
        [-0.80015806],
        [ 0.70025541]]),
 [array([0., 0., 0.]),
  array([[ 0.2  ],
         [-1.425],
         [ 2.   ]]),
  array([[ 2.2   ],
         [-0.825 ],
         [ 1.0875]]),
  array([[ 1.2875  ],
         [-0.053125],
         [-0.6125  ]]),
  array([[-0.4125   ],
         [-0.934375 ],
         [ 0.6859375]]),
  array([[ 0.8859375 ],
         [-1.45976563],
         [ 1.9453125 ]]),
  array([[ 2.1453125 ],
         [-0.49570312],
         [ 0.38417969]]),
  array([[ 0.58417969],
         [-0.25629883],
         [-0.39316406]]),
  array([[-0.19316406],
         [-1.23120117],
         [ 1.2876709 ]]),
  array([[ 1.4876709 ],
         [-1.19966431],
         [ 1.57756348]]),
  array([[ 1.77756348],
         [-0.28677368],
         [-0.08750305]]),
  array([[ 0.11249695],
         [-0.55809402],
         [ 0.07904968]]),
  array([[ 0.27904968],
         [-1.34898911],
         [ 1.60845604]]),
  array([[ 1.80845604],
         [-0.88336115],
      

b

In [23]:
%autoreload 2
A = [[1,0,-2],[-0.5,1,-0.25,],[1,-0.5,1]]
b = [0.2,-1.425,2]
x0 = np.zeros(len(b))
tol = 10e-22
max_iter = 300

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:06][INFO] i= 0 x: [0. 0. 0.]
[02-06 10:56:06][INFO] i= 1 x: [[ 0.2   -1.425  2.   ]]
[02-06 10:56:06][INFO] i= 2 x: [[ 4.2    -0.825   1.0875]]
[02-06 10:56:06][INFO] i= 3 x: [[ 2.375     0.946875 -2.6125  ]]
[02-06 10:56:06][INFO] i= 4 x: [[-5.025     -0.890625   0.0984375]]
[02-06 10:56:06][INFO] i= 5 x: [[ 0.396875   -3.91289062  6.5796875 ]]
[02-06 10:56:06][INFO] i= 6 x: [[13.359375    0.41835938 -0.35332031]]
[02-06 10:56:06][INFO] i= 7 x: [[ -0.50664063   5.16635742 -11.15019531]]
[02-06 10:56:06][INFO] i= 8 x: [[-22.10039062  -4.46586914   5.08981934]]
[02-06 10:56:06][INFO] i= 9 x: [[ 10.37963867 -11.20274048  21.86745605]]
[02-06 10:56:06][INFO] i= 10 x: [[ 43.93491211   9.23168335 -13.98100891]]
[02-06 10:56:06][INFO] i= 11 x: [[-27.76201782  17.04720383 -37.31907043]]
[02-06 10:56:06][INFO] i= 12 x: [[-74.43814087 -24.63577652  38.28561974]]
[02-06 10:56:06][INFO] i= 13 x: [[ 76.77123947 -29.0726655   64.12025261]]
[02-06 10:56:06][INFO] i= 14 x: [[128.44050522

(array([[-1.79225360e+43],
        [-4.51500391e+42],
        [ 6.72394565e+42]]),
 [array([0., 0., 0.]),
  array([[ 0.2  ],
         [-1.425],
         [ 2.   ]]),
  array([[ 4.2   ],
         [-0.825 ],
         [ 1.0875]]),
  array([[ 2.375   ],
         [ 0.946875],
         [-2.6125  ]]),
  array([[-5.025    ],
         [-0.890625 ],
         [ 0.0984375]]),
  array([[ 0.396875  ],
         [-3.91289062],
         [ 6.5796875 ]]),
  array([[13.359375  ],
         [ 0.41835938],
         [-0.35332031]]),
  array([[ -0.50664063],
         [  5.16635742],
         [-11.15019531]]),
  array([[-22.10039062],
         [ -4.46586914],
         [  5.08981934]]),
  array([[ 10.37963867],
         [-11.20274048],
         [ 21.86745605]]),
  array([[ 43.93491211],
         [  9.23168335],
         [-13.98100891]]),
  array([[-27.76201782],
         [ 17.04720383],
         [-37.31907043]]),
  array([[-74.43814087],
         [-24.63577652],
         [ 38.28561974]]),
  array([[ 76.77123947],

## Ejercicio 8

a

La matriz si es estrictamente dominante en la diagonal, cumple con la condición de que el elemento de la diagonal sea mayor que la suma del valor absoluto del resto de elementos de esa fila.

b

In [24]:
A = [
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
    [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
]
b = [220, 110, 110, 220, 110, 110, 110, 110,220, 110, 110, 220]
x0 = np.zeros(len(b))
tol = 10e-2
max_iter = 300
gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:06][INFO] i= 0 x: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[02-06 10:56:06][INFO] i= 1 x: [[55.  27.5 27.5 55.  27.5 27.5 27.5 27.5 55.  27.5 27.5 55. ]]
[02-06 10:56:06][INFO] i= 2 x: [[68.75  48.125 48.125 68.75  48.125 48.125 48.125 48.125 68.75  48.125
  48.125 68.75 ]]
[02-06 10:56:06][INFO] i= 3 x: [[79.0625  56.71875 56.71875 79.0625  56.71875 56.71875 56.71875 56.71875
  79.0625  56.71875 56.71875 79.0625 ]]
[02-06 10:56:06][INFO] i= 4 x: [[83.359375  61.4453125 61.4453125 83.359375  61.4453125 61.4453125
  61.4453125 61.4453125 83.359375  61.4453125 61.4453125 83.359375 ]]
[02-06 10:56:06][INFO] i= 5 x: [[85.72265625 63.70117188 63.70117188 85.72265625 63.70117188 63.70117188
  63.70117188 63.70117188 85.72265625 63.70117188 63.70117188 85.72265625]]
[02-06 10:56:06][INFO] i= 6 x: [[86.85058594 64.85595703 64.85595703 86.85058594 64.85595703 64.85595703
  64.85595703 64.85595703 86.85058594 64.85595703 64.85595703 86.85058594]]
[02-06 10:56:06][INFO] i= 7 x: [[87.427

(array([[87.98209548],
        [65.98209679],
        [65.98209679],
        [87.98209548],
        [65.98209679],
        [65.98209679],
        [65.98209679],
        [65.98209679],
        [87.98209548],
        [65.98209679],
        [65.98209679],
        [87.98209548]]),
 [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([[55. ],
         [27.5],
         [27.5],
         [55. ],
         [27.5],
         [27.5],
         [27.5],
         [27.5],
         [55. ],
         [27.5],
         [27.5],
         [55. ]]),
  array([[68.75 ],
         [48.125],
         [48.125],
         [68.75 ],
         [48.125],
         [48.125],
         [48.125],
         [48.125],
         [68.75 ],
         [48.125],
         [48.125],
         [68.75 ]]),
  array([[79.0625 ],
         [56.71875],
         [56.71875],
         [79.0625 ],
         [56.71875],
         [56.71875],
         [56.71875],
         [56.71875],
         [79.0625 ],
         [56.71875],
         [56.7187

c

In [25]:
gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-06 10:56:07][INFO] i= 0 x: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[02-06 10:56:07][INFO] i= 1 x: [[55.         41.25       37.8125     64.453125   41.25       43.61328125
  37.8125     38.40332031 64.453125   43.61328125 38.40332031 75.50415039]]
[02-06 10:56:07][INFO] i= 2 x: [[75.625      55.859375   57.578125   80.29785156 55.859375   57.17529297
  57.578125   60.66986084 80.29785156 57.17529297 60.66986084 84.46128845]]
[02-06 10:56:07][INFO] i= 3 x: [[82.9296875  62.62695312 63.23120117 85.10162354 62.62695312 63.94287109
  63.23120117 64.60103989 85.10162354 63.94287109 64.60103989 87.13597775]]
[02-06 10:56:07][INFO] i= 4 x: [[86.31347656 64.88616943 64.99694824 87.23495483 64.88616943 65.45899868
  64.99694824 65.64874411 87.23495483 65.45899868 65.64874411 87.7769357 ]]
[02-06 10:56:07][INFO] i= 5 x: [[87.44308472 65.61000824 65.71124077 87.79255986 65.61000824 65.86032599
  65.71124077 65.90931542 87.79255986 65.86032599 65.90931542 87.94241035]]
[02-06 10:56:07][INFO] i= 

(array([[87.98217949],
        [65.98985217],
        [65.99375664],
        [87.99604191],
        [65.98985217],
        [65.9974727 ],
        [65.99375664],
        [65.99838442],
        [87.99604191],
        [65.9974727 ],
        [65.99838442],
        [87.99896428]]),
 [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([[55.        ],
         [41.25      ],
         [37.8125    ],
         [64.453125  ],
         [41.25      ],
         [43.61328125],
         [37.8125    ],
         [38.40332031],
         [64.453125  ],
         [43.61328125],
         [38.40332031],
         [75.50415039]]),
  array([[75.625     ],
         [55.859375  ],
         [57.578125  ],
         [80.29785156],
         [55.859375  ],
         [57.17529297],
         [57.578125  ],
         [60.66986084],
         [80.29785156],
         [57.17529297],
         [60.66986084],
         [84.46128845]]),
  array([[82.9296875 ],
         [62.62695312],
         [63.23120117],
         [8