# Tarea 11

Repositorio: https://github.com/KennethJYS/Tarea-11

In [9]:
%load_ext autoreload
import numpy as np
from src import gauss_jacobi,gauss_seidel

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Ejercicio 1

a

In [10]:
%autoreload 2
A = [[3,-1,1],[3,6,2],[3,3,7]]
b = np.array([1,0,4])
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-05 21:53:47][INFO] i= 0 x: [0. 0. 0.]
[02-05 21:53:47][INFO] i= 1 x: [[0.33333333 0.         0.57142857]]
[02-05 21:53:47][INFO] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]


(array([[ 0.14285714],
        [-0.35714286],
        [ 0.42857143]]),
 [array([0., 0., 0.]),
  array([[0.33333333],
         [0.        ],
         [0.57142857]]),
  array([[ 0.14285714],
         [-0.35714286],
         [ 0.42857143]])])

b

In [11]:
%autoreload 2
A = [[10,-1,0],[-1,10,-2],[0,-2,10]]
b = np.array([9,7,6],dtype=float)
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-05 21:53:47][INFO] i= 0 x: [0. 0. 0.]
[02-05 21:53:47][INFO] i= 1 x: [[0.9 0.7 0.6]]
[02-05 21:53:47][INFO] i= 2 x: [[0.97 0.91 0.74]]


(array([[0.97],
        [0.91],
        [0.74]]),
 [array([0., 0., 0.]),
  array([[0.9],
         [0.7],
         [0.6]]),
  array([[0.97],
         [0.91],
         [0.74]])])

c

In [12]:
%autoreload 2
A = [[10,-5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]]
b = np.array([16,25,-11,-11],dtype=float)
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-05 21:53:47][INFO] i= 0 x: [0. 0. 0. 0.]
[02-05 21:53:47][INFO] i= 1 x: [[ 1.6    2.5   -1.375 -2.2  ]]
[02-05 21:53:47][INFO] i= 2 x: [[ 2.85   1.15  -0.4   -2.475]]


(array([[ 2.85 ],
        [ 1.15 ],
        [-0.4  ],
        [-2.475]]),
 [array([0., 0., 0., 0.]),
  array([[ 1.6  ],
         [ 2.5  ],
         [-1.375],
         [-2.2  ]]),
  array([[ 2.85 ],
         [ 1.15 ],
         [-0.4  ],
         [-2.475]])])

d

In [13]:
%autoreload 2
A = [[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]
b = np.array([6,6,6,6,6],dtype=float)
x0=np.zeros(len(b))
max_iter = 3
tol = 10e-6

gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

[02-05 21:53:47][INFO] i= 0 x: [0. 0. 0. 0. 0.]
[02-05 21:53:47][INFO] i= 1 x: [[ 1.5 -2.   1.2  1.5  1.5]]
[02-05 21:53:47][INFO] i= 2 x: [[ 1.325 -1.6    1.6    1.675  2.425]]


(array([[ 1.325],
        [-1.6  ],
        [ 1.6  ],
        [ 1.675],
        [ 2.425]]),
 [array([0., 0., 0., 0., 0.]),
  array([[ 1.5],
         [-2. ],
         [ 1.2],
         [ 1.5],
         [ 1.5]]),
  array([[ 1.325],
         [-1.6  ],
         [ 1.6  ],
         [ 1.675],
         [ 2.425]])])

## Ejercicio 2